# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes
NKRO_ENABLE = yes
KEYBOARD_SHARED_EP = yes
OLED_ENABLE = no
# OLED_DRIVER = SSD1306
WPM_ENABLE = no
EXTRAKEY_ENABLE = yes
ENCODER_ENABLE = no
RGBLIGHT_ENABLE = no
# RGBLIGHT_DRIVER = WS2812
